apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: ibm-cpd-datastage-remote-operator
  name: {{ include "datastage.apiKeySecret" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc }}
  service-id: {{ default "iamapikey" .Values.serviceId | b64enc }}
  {{- if .Values.mcspAccountId }}
  mcsp-account-id: {{ .Values.mcspAccountId | b64enc }}
  {{- end }}
