{{- if .Values.db2zLicense }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: ibm-cpd-datastage-remote-operator
  name: datastage-db2z-license
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db2consv_ee.lic: {{ .Values.db2zLicense | b64enc }}
{{- end }}
