{{- if and .Values.username .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: ibm-cpd-datastage-remote-operator
  name: datastage-pull-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"icr.io":{"username":"%s","password":"%s","email":"cpd@us.ibm.com","auth":"%s"}}}` .Values.username .Values.password (printf "%s:%s" .Values.username .Values.password | b64enc) | b64enc }}
{{- end }}
