apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  name: ibm-cpd-datastage-remote-operator-serviceaccount
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: ibm-cpd-datastage-remote-operator-sa
    app.kubernetes.io/managed-by: ibm-cpd-datastage-remote-operator
    app.kubernetes.io/name: ibm-cpd-datastage-remote-operator-sa
imagePullSecrets:
  - name: ibm-entitlement-key
  - name: datastage-pull-secret
